{{- if .Values.headlessService.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "weecuba-statefulset-service.fullname" . }}-headless
  namespace: {{ include "weecuba-statefulset-service.namespace" . }}
  labels:
    {{- include "weecuba-statefulset-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
  annotations:
    # Use this annotation in addition to the actual publishNotReadyAddresses
    # field below because the annotation will stop being respected soon but the
    # field is broken in some versions of Kubernetes:
    # https://github.com/kubernetes/kubernetes/issues/58662
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  # We want all pods in the StatefulSet to have their addresses published for
  # the sake of the other Postgresql pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: {{ .Values.headlessService.publishNotReadyAddresses }}
  {{- with .Values.headlessService.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "weecuba-statefulset-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: primary
{{- end }}
