{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "weecuba-dotnet-service.serviceAccountName" . }}
  namespace: {{ include "weecuba-dotnet-service.namespace" . }}
  labels:
    {{- include "weecuba-dotnet-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
