{{- if .Values.certificate.create }}
  {{- $jks := .Values.certificate.keystores.jks }}
  {{- $jksSecretName := $jks.passwordSecretRef.name }}
  {{- $jksSecretKey := $jks.passwordSecretRef.key }}
  {{- if and $jks.create $jksSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $jksSecretName }}
  namespace: {{ include "swift-deployment-webapi.namespace" . }}
  annotations:
    argocd.argoproj.io/compare-options: "IgnoreExtraneous"
    argocd.argoproj.io/sync-options: "Validate=false"   
  labels:
    {{- include "swift-deployment-webapi.labels" . | nindent 4 }}  
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $jksSecretName) | default dict }}
  {{- $existingData := (get $existingSecret "data") | default dict }}

  {{ $jksSecretKey }}: {{ (get $existingData $jksSecretKey) | default (randAlphaNum 32 | b64enc) | quote }}
  {{- end }}
{{- end }}