{{- if .Values.certificate.create }}
  {{- if and (hasKey .Values.certificate.keystores "pkcs12") .Values.certificate.keystores.pkcs12.create .Values.certificate.keystores.pkcs12.passwordSecretRef.name }}
    {{- $pkcs12Secret := .Values.certificate.keystores.pkcs12.passwordSecretRef.name }}
    {{- if not (lookup "v1" "Secret" .Release.Namespace $pkcs12Secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certificate.keystores.pkcs12.passwordSecretRef.name }}
  namespace: {{ include "swift-deployment-webapi.namespace" . }}
type: Opaque
data:
  {{ .Values.certificate.keystores.pkcs12.passwordSecretRef.key }}: {{ randAlphaNum 32 | b64enc }}
    {{- end }}
  {{- end }}
{{- end }}
