{{- if .Values.certificate.create }}
  {{- $pkcs12 := .Values.certificate.keystores.pkcs12 }}
  {{- $pkcs12SecretName := $pkcs12.passwordSecretRef.name }}
  {{- $pkcs12SecretKey := $pkcs12.passwordSecretRef.key }}
  {{- if and $pkcs12.create $pkcs12SecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pkcs12SecretName }}
  namespace: {{ include "swift-deployment-webapi.namespace" . }}
  annotations:
    argocd.argoproj.io/compare-options: "IgnoreExtraneous"
    argocd.argoproj.io/sync-options: "Validate=false"  
  labels:
    {{- include "swift-deployment-webapi.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $pkcs12SecretName) | default dict }}
  {{- $existingData := (get $existingSecret "data") | default dict }}

  {{ $pkcs12SecretKey }}: {{ (get $existingData $pkcs12SecretKey) | default (randAlphaNum 32 | b64enc) | quote }}
  {{- end }}
{{- end }}