{{- if .Values.certificate.create }}
  {{- $pkcs12 := .Values.certificate.keystores.pkcs12 }}
  {{- $pkcs12SecretName := $pkcs12.passwordSecretRef.name }}
  {{- $pkcs12SecretKey := $pkcs12.passwordSecretRef.key }}
  {{- if and $pkcs12.create $pkcs12SecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pkcs12SecretName }}
  namespace: {{ include "swift-deployment-webapi.namespace" . }}
type: Opaque
data:
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $pkcs12SecretName }}
  {{- if and $existingSecret (index $existingSecret.data $pkcs12SecretKey) }}
    {{ $pkcs12SecretKey }}: {{ index $existingSecret.data $pkcs12SecretKey }}
  {{- else }}
    {{ $pkcs12SecretKey }}: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}