{{- if .Values.certificate.create }}
  {{- $jks := .Values.certificate.keystores.jks }}
  {{- $jksSecretName := $jks.passwordSecretRef.name }}
  {{- $jksSecretKey := $jks.passwordSecretRef.key }}
  {{- if and $jks.create $jksSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $jksSecretName }}
  namespace: {{ include "swift-deployment-webapi.namespace" . }}
type: Opaque
data:
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $jksSecretName }}
  {{- if and $existingSecret (index $existingSecret.data $jksSecretKey) }}
    {{ $jksSecretKey }}: {{ index $existingSecret.data $jksSecretKey }}
  {{- else }}
    {{ $jksSecretKey }}: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}