{{- if .Values.certificate.create }}
  {{- if and (hasKey .Values.certificate.keystores "jks") .Values.certificate.keystores.jks.create .Values.certificate.keystores.jks.passwordSecretRef.name }}
    {{- $jksSecret := .Values.certificate.keystores.jks.passwordSecretRef.name }}
    {{- if not (lookup "v1" "Secret" .Release.Namespace $jksSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certificate.keystores.jks.passwordSecretRef.name }}
  namespace: {{ include "swift-deployment-webapi.namespace" . }}
type: Opaque
data:
  {{ .Values.certificate.keystores.jks.passwordSecretRef.key }}: {{ randAlphaNum 32 | b64enc }}
    {{- end }}
  {{- end }}
{{- end }}
